from __future__ import annotations

from enum import StrEnum


class ExperimentStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WorkerStage(StrEnum):
    LOAD_DATA = "LOAD_DATA"
    NORMALIZE_DATA = "NORMALIZE_DATA"
    BUILD_BACKTEST_WINDOWS = "BUILD_BACKTEST_WINDOWS"
    TRAIN_BASELINES = "TRAIN_BASELINES"
    TRAIN_AUTOGLUON = "TRAIN_AUTOGLUON"
    GENERATE_BACKTEST_PREDICTIONS = "GENERATE_BACKTEST_PREDICTIONS"
    CALCULATE_METRICS = "CALCULATE_METRICS"
    REFIT_BEST_MODEL = "REFIT_BEST_MODEL"
    GENERATE_FUTURE_FORECAST = "GENERATE_FUTURE_FORECAST"
    BUILD_EXPORT = "BUILD_EXPORT"
    COMPLETE = "COMPLETE"
